---
stages:
- name: Build Stage(Stub)
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: target
    build_type: maven
    build_script: |-
      #!/bin/bash
      # build the application 
      mvn -B package
