---
stages:
- name: Build Stage(Stub)
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    directory_offset: SFDParent
    artifact_dir: ${WORKSPACE}/StubParent/StubEar/target
    build_type: maven
    script: |-
      #!/bin/bash
      # build the application 
      mvn -B package       
      
- name: Deploy Stage(Stub)
  inputs:
  - type: job
    stage: Build Stage(Stub)
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: AIF_Stub
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -p StubEar-0.0.1-SNAPSHOT.ear -m 256M --no-start
      cf set-env ${CF_APP} JBP_CONFIG_LIBERTY "app_archive: {features: [cdi-1.2, concurrent-1.0, jaxb-2.2, jndi-1.0, jaxws-2.2, jsonp-1.0, jaxrs-2.0, javaMail-1.5, json-1.0, jsf-2.2, localConnector-1.0, servlet-3.1, wasJmsClient-2.0, wasJmsServer-1.0, websocket-1.1]}"
      cf start "${CF_APP}"
      # ==== enable shell ==============
      #echo === "${CF_APP}" ===
      #cf set-env "${CF_APP}" BLUEMIX_APP_MGMT_ENABLE devconsole+shell
      #cf restage "${CF_APP}"
      # ==== enable logs ===============
      #cf logs "${CF_APP}"
