---
stages:
- name: Build Stage(Stub)
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: JAVA_HOME
    value: /opt/IBM/java8
    type: text
  jobs:
  - name: Build
    type: builder
    directory_offset: SFDParent
    artifact_dir: ${WORKSPACE}/StubParent/StubEar/target
    build_type: maven
    script: |-
      #!/bin/bash
      # build the application 
      mvn -B package       
      
- name: Deploy Stage(Stub)
  inputs:
  - type: job
    stage: Build Stage(Stub)
    job: Build
  triggers:
  - type: stage
  properties:
  - name: JAVA_HOME
    value: /opt/IBM/java8
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: AIF_Stub
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -p StubEar-0.0.1-SNAPSHOT.ear -m 256M --no-start
      cf set-env ${CF_APP} JBP_CONFIG_LIBERTY "app_archive: {features: [cdi-1.2, concurrent-1.0, jaxb-2.2, jndi-1.0, jaxws-2.2, jsonp-1.0, jaxrs-2.0, javaMail-1.5, json-1.0, jsf-2.2, localConnector-1.0, servlet-3.1, wasJmsClient-2.0, wasJmsServer-1.0, websocket-1.1]}"
      cf start "${CF_APP}"
      # ==== enable shell ==============
      #echo === "${CF_APP}" ===
      #cf set-env "${CF_APP}" BLUEMIX_APP_MGMT_ENABLE devconsole+shell
      #cf restage "${CF_APP}"
      # ==== enable logs ===============
      #cf logs "${CF_APP}"
      
- name: Build Stage(AIF)
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: JAVA_HOME
    value: /opt/IBM/java8
    type: text
  jobs:
  - name: Build
    type: builder
    directory_offset: AIFParent
    artifact_dir: ${WORKSPACE}/AIFParent/AIF/target
    build_type: maven
    script: |-
      #!/bin/bash
      #mvn -B package -e -Pbluemix
      mvn -B package -e 
      cp -r ${WORKSPACE}/wlp ${WORKSPACE}/AIFParent/AIF/target/wlp    
      
- name: Deploy Stage(AIF)
  inputs:
  - type: job
    stage: Build Stage(AIF)
    job: Build
  triggers:
  - type: stage
  properties:
  - name: JAVA_HOME
    value: /opt/IBM/java8
    type: text
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: AIF
    script: |
      #!/bin/bash
      #サーバーパッケージ
      cp AIF-0.0.1-SNAPSHOT.war wlp/usr/servers/defaultServer/apps/AIF-0.0.1-SNAPSHOT.war
      chmod +x wlp/bin/*
      wlp/bin/server package defaultServer --archive=was.zip --include=usr
      # アプリのデプロイ、更新
      #
      cf push "${CF_APP}" -p wlp/usr/servers/defaultServer/was.zip -m 1024M -t 180 --no-start
      # Liberty用の環境設定
      cf set-env ${CF_APP} JBP_CONFIG_LIBERTY "app_archive: {features: [cdi-1.2, concurrent-1.0, jaxb-2.2, jndi-1.0, jaxws-2.2, jsonp-1.0, jaxrs-2.0, javaMail-1.5, json-1.0, jsf-2.2, localConnector-1.0, servlet-3.1, wasJmsClient-2.0, wasJmsServer-1.0, websocket-1.1,wmqJmsClient-2.0]}"
      # システム変数定義
      cf set-env ${CF_APP} JVM_ARGS "-Dcom.ibm.cis.aif.log.AIFLogger.isDumpEnable=true -Dcom.ibm.cis.aif.log.AIFLogger.vcapServiceName=cloudantNoSQLDB -Dcom.ibm.cis.aif.interceptor.OBStub.restStub=http://aif-devops-stub.w3ibm.mybluemix.net/StubAppRS"
      # 上記設定の反映
      cf restage ${CF_APP}
      # アプリの起動
      cf start ${CF_APP}

- name: setEnv
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: stage
  properties:
  - name: JAVA_HOME
    value: /opt/IBM/java8
    type: text
  - name: PATH
    value: ${JAVA_HOME}/bin:$PATH
    type: text
  jobs:
  - name: Build
    type: builder
    directory_offset: SFDParent/SFDEnvSet
    artifact_dir: target
    build_type: maven
    script: |-
      #!/bin/bash
      URL=https://aif-mq-test.mybluemix.net/aif
      LIST=${WORKSPACE}/SFDParent/SFDEnvSet/URIConvert/BluemixConvertList.txt
      mvn install
      # 実行
      java -cp "${ARCHIVE_DIR}/lib/*" com.ibm.cis.aif.sfd.URIConverter.OutboundURIConverter "$LIST" "$URL"

- name: Test Stage
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    tester_type: simple
    script: |-
      #!/bin/bash
      # ここでテストを起動します
      AIF_URL=<your aif url>
      CLOUDANT_URL=<your cloudant url>
      JMeter_Path=${WORKSPACE}/SFDParent/apache-jmeter-2.8/bin/jmeter
      # Jmeter の実行時のバージョンを強制的にJava8にする。
      export JAVA_HOME=/opt/IBM/java8
      export PATH=${JAVA_HOME}/bin:$PATH
      echo ======================================
      javac -version
      echo ======================================
      mvn install:install-file -Dfile=${WORKSPACE}/AIFParent/lib/com.ibm.cis.aif.jar -DgroupId=AIF -DartifactId=com.ibm.cis.aif -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
      mvn install:install-file -Dfile=${WORKSPACE}/AIFParent/lib/com.ibm.cis.aif.tools.et.jar -DgroupId=AIF -DartifactId=com.ibm.cis.aif.tools.et -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
      mvn integration-test  -Dtarget.host=${AIF_URL} -Dtarget.port=80 -Dcom.ibm.cis.aif.sfd.CloudantAccessor.dbName=aifdump -DJMeterPath=${JMeter_Path} -Dcom.ibm.cis.aif.sfd.SFDTestCase.contextURL=${AIF_URL}/aif -Dcom.ibm.cis.aif.sfd.CloudantAccessor.url=${CLOUDANT_URL}
    directory_offset: SFDParent/SFDTester
    enable_coverage: true
    test_file_pattern: 'target/failsafe-reports/TEST-*.xml'
